# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind
  
variables:
  IMAGE: "$PERSONAL_REGISTRY/$IMAGE_NAME"

# before_script:
#   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $PERSONAL_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$IMAGE" .
    - docker push "$IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
